name: templates
version: '1.0.2'
main: org.ley.menu.tools.BukkitPluginMainClass
api-version: '1.21'

permissions:
  menu.user:
    default: true

commands:
  menu:
    permission: "ley.debug.templates"